repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ["--filter-files"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-j 0"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-crlf

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        language_version: python3
      - id: check-added-large-files
        language_version: python3
      - id: check-ast
        language_version: python3
      - id: check-yaml
        language_version: python3
      - id: check-json
        language_version: python3
      - id: detect-private-key
        language_version: python3
